# hf-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: hf-download
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  imagePullSecrets:
  - name: regcred
  restartPolicy: Never
  containers:
  - name: hf-download
    image: myregistry.com/hfcli
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    env: 
    - name: HF_HOME 
      value: /model/.cache/huggingface
    command:
    - hf
    args:
    - download
    - google-t5/t5-small
    - config.json
    - generation_config.json
    - model.safetensors
    - tokenizer_config.json
    - tokenizer.json
    - spiece.model
    - --local-dir
    - /model/t5-small
    volumeMounts:
    - name: model-volume
      mountPath: /model
  volumes:
  - name: model-volume
    persistentVolumeClaim:
      claimName: model-pvc
